name: PetClinic CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package
    
    - name: Run tests
      run: ./mvnw test
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-app
        path: target/*.jar